export { default as UserInformation} from './user-information'
export { default as DeliveryMethods } from './delivery-methods'
export { default as PaymentMethods } from './payment-methods'
export { default as ExtraNote } from './extra-note'
export { default as Promocode } from './promocode'
export { default as Address } from './address'
export { default as Summary } from './summary'